idp:
    appId: ${APP_ID:fubar}
    entityId: ${ENTITY_ID:ch:so:agi:avgbs:ssocircle:sp}
    postLogoutURL: ${POST_LOGOUT_URL:#{'/'}}
    metadataURL: ${IDP_METADATA_URL:https://idp.ssocircle.com/meta-idp.xml}

server:
    port: 8443
    ssl:
            key-alias: spring
            key-store: classpath:keystore.jks
            key-store-password: secret
spring:
    main:
        bannerMode: 'OFF'
    thymeleaf:
        cache: false

